#ifndef P101_OBSERVE_CONSTANTS_H
#define P101_OBSERVE_CONSTANTS_H

#include <p101_env/env.h>

#define DEFAULT_REPORT_PREFIX "p101-observe"

/* The shared p101 fault/logging variables are owned by lib_env; these are
 * local spellings of the one definition in <p101_env/env.h>. */
#define RESOURCE_LOG_ENV P101_ENV_RESOURCE_LOG_ENV
#define CALL_LOG_ENV P101_ENV_CALL_LOG_ENV
#define CALL_LOG_ARGS_ENV P101_ENV_CALL_LOG_ARGS_ENV
#define CALL_LOG_RESULT_ENV P101_ENV_CALL_LOG_RESULT_ENV
#define FAULT_CALL_ENV P101_ENV_FAULT_CALL_ENV
#define FAULT_ERRNO_ENV P101_ENV_FAULT_ERRNO_ENV
#define FAULT_LOG_ENV P101_ENV_FAULT_LOG_ENV
#define FAULT_NAME_ENV P101_ENV_FAULT_NAME_ENV
#define FAULT_MODE_ENV P101_ENV_FAULT_MODE_ENV
#define FAULT_AMOUNT_ENV P101_ENV_FAULT_AMOUNT_ENV
#define FAULT_REPEAT_ENV P101_ENV_FAULT_REPEAT_ENV

/* The child-side names are the p101-observe launch protocol, not lib_env. */
#define CHILD_FAULT_CALL_ENV "P101_OBSERVE_CHILD_FAULT_CALL"
#define CHILD_FAULT_ERRNO_ENV "P101_OBSERVE_CHILD_FAULT_ERRNO"
#define CHILD_FAULT_LOG_ENV "P101_OBSERVE_CHILD_FAULT_LOG"
#define CHILD_FAULT_NAME_ENV "P101_OBSERVE_CHILD_FAULT_NAME"
#define CHILD_FAULT_MODE_ENV "P101_OBSERVE_CHILD_FAULT_MODE"
#define CHILD_FAULT_AMOUNT_ENV "P101_OBSERVE_CHILD_FAULT_AMOUNT"
#define CHILD_FAULT_REPEAT_ENV "P101_OBSERVE_CHILD_FAULT_REPEAT"

enum
{
    MSG_LEN              = 256,
    RUN_ID_LEN           = 128,
    READ_BUF_LEN         = 4096,
    REPORT_TOOL_ARGV_LEN = 5,
    EXEC_FAILURE         = 127,
    REPORT_DIR_MODE      = 0755,
    REPORT_FILE_MODE     = 0644,
    EXIT_FINDINGS        = 1,
    EXIT_TROUBLE         = 2
};

#endif    // P101_OBSERVE_CONSTANTS_H
