#ifndef P101_OBSERVE_CONSTANTS_H
#define P101_OBSERVE_CONSTANTS_H

#define DEFAULT_REPORT_PREFIX "p101-observe"
#define DEFAULT_TRACKER_PATH "p101-resource-tracker"
#define DEFAULT_TRACE_PATH "p101-trace"
#define DEFAULT_REPORT_PATH "p101-report"
#define RESOURCE_LOG_ENV "P101_RESOURCE_LOG"
#define CALL_LOG_ENV "P101_CALL_LOG"
#define CALL_LOG_ARGS_ENV "P101_CALL_LOG_ARGS"
#define CALL_LOG_RESULT_ENV "P101_CALL_LOG_RESULT"
#define FAULT_CALL_ENV "P101_FAULT_CALL"
#define FAULT_ERRNO_ENV "P101_FAULT_ERRNO"
#define FAULT_LOG_ENV "P101_FAULT_LOG"
#define FAULT_NAME_ENV "P101_FAULT_NAME"
#define CHILD_FAULT_CALL_ENV "P101_OBSERVE_CHILD_FAULT_CALL"
#define CHILD_FAULT_ERRNO_ENV "P101_OBSERVE_CHILD_FAULT_ERRNO"
#define CHILD_FAULT_LOG_ENV "P101_OBSERVE_CHILD_FAULT_LOG"
#define CHILD_FAULT_NAME_ENV "P101_OBSERVE_CHILD_FAULT_NAME"
#define JSON_RECORDS "\"records\""
#define JSON_FD_LEAKS "\"fd_leaks\""
#define JSON_ALLOCATION_LEAKS "\"allocation_leaks\""
#define JSON_BAD_RELEASES "\"bad_releases\""
#define JSON_EXEC_INHERITANCES "\"exec_inheritances\""
#define JSON_MALFORMED "\"malformed\""
#define JSON_BAD_VERSION "\"bad_version\""
#define JSON_REFUSED "\"refused\""

enum
{
    MSG_LEN          = 256,
    READ_BUF_LEN     = 4096,
    JSON_BUF_LEN     = 65536,
    JSON_NUMBER_BASE = 10,
    EXEC_FAILURE     = 127,
    REPORT_DIR_MODE  = 0755,
    REPORT_FILE_MODE = 0644,
    EXIT_FINDINGS    = 1,
    EXIT_TROUBLE     = 2
};

#endif    // P101_OBSERVE_CONSTANTS_H
