#ifndef P101_OBSERVE_CONSTANTS_H
#define P101_OBSERVE_CONSTANTS_H

#define DEFAULT_REPORT_PREFIX "p101-observe"
#define DEFAULT_TRACKER_PATH "p101-resource-tracker"
#define DEFAULT_TRACE_PATH "p101-trace"
#define DEFAULT_REPORT_PATH "p101-report"
#define RESOURCE_LOG_ENV "P101_RESOURCE_LOG"
#define CALL_LOG_ENV "P101_CALL_LOG"
#define EVENT_LOG_VERSION_ENV "P101_TOOL_EVENT_LOG_VERSION"
#define EVENT_LOG_VERSION_VALUE "3"
#define CALL_LOG_ARGS_ENV "P101_CALL_LOG_ARGS"
#define CALL_LOG_RESULT_ENV "P101_CALL_LOG_RESULT"
#define FAULT_CALL_ENV "P101_FAULT_CALL"
#define FAULT_ERRNO_ENV "P101_FAULT_ERRNO"
#define FAULT_LOG_ENV "P101_FAULT_LOG"
#define FAULT_NAME_ENV "P101_FAULT_NAME"
#define FAULT_MODE_ENV "P101_FAULT_MODE"
#define FAULT_AMOUNT_ENV "P101_FAULT_AMOUNT"
#define FAULT_REPEAT_ENV "P101_FAULT_REPEAT"
#define CHILD_FAULT_CALL_ENV "P101_OBSERVE_CHILD_FAULT_CALL"
#define CHILD_FAULT_ERRNO_ENV "P101_OBSERVE_CHILD_FAULT_ERRNO"
#define CHILD_FAULT_LOG_ENV "P101_OBSERVE_CHILD_FAULT_LOG"
#define CHILD_FAULT_NAME_ENV "P101_OBSERVE_CHILD_FAULT_NAME"
#define CHILD_FAULT_MODE_ENV "P101_OBSERVE_CHILD_FAULT_MODE"
#define CHILD_FAULT_AMOUNT_ENV "P101_OBSERVE_CHILD_FAULT_AMOUNT"
#define CHILD_FAULT_REPEAT_ENV "P101_OBSERVE_CHILD_FAULT_REPEAT"
enum
{
    MSG_LEN          = 256,
    RUN_ID_LEN       = 128,
    READ_BUF_LEN     = 4096,
    JSON_BUF_LEN     = 65536,
    EXEC_FAILURE     = 127,
    REPORT_DIR_MODE  = 0755,
    REPORT_FILE_MODE = 0644,
    EXIT_FINDINGS    = 1,
    EXIT_TROUBLE     = 2
};

#endif    // P101_OBSERVE_CONSTANTS_H
